modLoader="javafml"
loaderVersion="[43,)"
license="Massachusetts Institute of Technology (MIT)"

[[mods]]
modId="${modid}"
version="${mc_version}-${mod_version}"
displayName="${mod_name}"
logoFile="celestisynth_logo.png"
authors="${mod_authors}"
credits="${mod_authors}"
description="${mod_description}"

# Base
[[dependencies.celestisynth]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.celestisynth]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

# Dependencies (Required)
[[dependencies.celestisynth]]
modId="geckolib3"
mandatory=true
versionRange="${geckolib_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.celestisynth]]
modId="playeranimator"
mandatory=true
versionRange="${player_animator_version_range}"
ordering="NONE"
side="BOTH"

# Dependencies (Optional)
[[dependencies.celestisynth]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.celestisynth]]
modId="jeresources"
mandatory=false
versionRange="jer_version_range"
ordering="AFTER"
side="BOTH"

[[dependencies.celestisynth]]
modId="jeed"
mandatory=false
versionRange="${jeed_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.celestisynth]]
modId="jade"
mandatory=false
versionRange="${jade_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.celestisynth]]
modId="lazydfu"
mandatory=false
versionRange="${lazydfu_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.celestisynth]]
modId="configured"
mandatory=false
versionRange="${configured_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.celestisynth]]
modId="catalogue"
mandatory=false
versionRange="${catalogue_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.celestisynth]]
modId="gamemenumodoption"
mandatory=false
versionRange="${gmmo_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.celestisynth]]
modId="appleskin"
mandatory=false
versionRange="${appleskin_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.celestisynth]]
modId="shutupexperimentalsettings"
mandatory=false
versionRange="${sues_version_range}"
ordering="AFTER"
side="CLIENT"