modLoader="javafml"
loaderVersion="[43,)"
license="Massachusetts Institute of Technology (MIT)"

[[mods]]
modId="celestisynth"
version="${file.jarVersion}"
displayName="Celestisynth"
logoFile="celestisynth.png"
authors="AquTheSeal"
credits="AquTheSeal, YeoXuHang"

description='''
Celestisynth is a Minecraft mod that focuses in adding brand-new and unique weapons with special abilities for you to play around with!
'''

[[dependencies.celestisynth]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.celestisynth]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.celestisynth]]
modId="playeranimator"
mandatory=true
versionRange="[1,)"
ordering="AFTER"

[[dependencies.celestisynth]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.40,)"
ordering="AFTER"
