modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${modid}"
version="${mc_version}-${mod_version}"
displayName="${mod_name}"
logoFile="celestisynth_logo.png"
authors="${mod_authors}"
credits="${mod_authors}"
description='''${mod_description}'''

# Base
[[dependencies."${modid}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependencies (Required)
[[dependencies."${modid}"]]
    modId="geckolib"
    mandatory=true
    versionRange="${geckolib_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="playeranimator"
    mandatory=true
    versionRange="${player_animator_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependencies (Optional)
#   COMMON
[[dependencies."${modid}"]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jeresources"
    mandatory=false
    versionRange="jer_version_range"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jeed"
    mandatory=false
    versionRange="${jeed_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="jade"
    mandatory=false
    versionRange="${jade_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${modid}"]]
    modId="forgeconfigscreens"
    mandatory=false
    versionRange="${config_menus_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${modid}"]]
    modId="gamemenumodoption"
    mandatory=false
    versionRange="${gmmo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies."${modid}"]]
    modId="appleskin"
    mandatory=false
    versionRange="${appleskin_version_range}"
    ordering="NONE"
    side="CLIENT"