package org.thecelestialworkshop.celestisynth.common.registry;

import org.thecelestialworkshop.celestisynth.Celestisynth;
import net.minecraft.core.Holder;
import net.minecraft.core.RegistryAccess;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.enchantment.Enchantment;

import java.util.List;
import java.util.Optional;

/**
 * Enchantments are data-driven as of 1.21; definitions live in
 * {@code data/celestisynth/enchantment/} (generated by datagen) and gameplay
 * logic is triggered from event handlers.
 */
public class CSEnchantments {
    public static final ResourceKey<Enchantment> PULSATION = ResourceKey.create(Registries.ENCHANTMENT, Celestisynth.prefix("pulsation"));

    public static final List<ResourceKey<Enchantment>> ALL = List.of(PULSATION);

    public static Optional<Holder.Reference<Enchantment>> getHolder(RegistryAccess registryAccess, ResourceKey<Enchantment> key) {
        return registryAccess.registryOrThrow(Registries.ENCHANTMENT).getHolder(key);
    }
}
